# Generated by Django 4.2.3 on 2023-08-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_batch_branch_district_enquireysource_followupstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
