# Generated by Django 4.2.3 on 2023-08-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquirey_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquireysoursename', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'enquiry sources',
                'verbose_name_plural': 'enquiry sources',
            },
        ),
        migrations.CreateModel(
            name='follow_up_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupstatusname', models.CharField(max_length=100, null=True)),
                ('followupstatus', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'follow up status',
                'verbose_name_plural': 'follow up statuses',
            },
        ),
        migrations.CreateModel(
            name='master_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'master data',
                'verbose_name_plural': 'master data',
            },
        ),
        migrations.DeleteModel(
            name='enquireysource',
        ),
        migrations.DeleteModel(
            name='followupstatus',
        ),
        migrations.DeleteModel(
            name='masterdata',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name_plural': 'qualifications'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'states'},
        ),
        migrations.AddField(
            model_name='batch',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='adress1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='adress2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
